env:
  - DB=mysql
  - DB=postgres

before_script:
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'create database sqlalchemy_continuum_test;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database sqlalchemy_continuum_test;'; fi"

language: python
python:
  - 2.6
  - 2.7
  - 3.3
install:
  - pip install -e  ".[test]"
script:
  - python setup.py test
